WITH RECURSIVE GenerationHierarchy AS (
  SELECT ID, PARENT_ID, 1 AS GENERATION
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL
  
  UNION ALL
  
  SELECT child.ID, child.PARENT_ID, parent.GENERATION + 1 AS GENERATION
  FROM ECOLI_DATA AS child
  JOIN GenerationHierarchy AS parent ON child.PARENT_ID = parent.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GenerationHierarchy
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION;